# Generated by Django 5.0.3 on 2024-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashuser',
            name='birth_year',
            field=models.TextField(blank=True, default=''),
        ),
    ]
