# Generated by Django 5.0.3 on 2024-04-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist_uri',
        ),
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='added_by_hash_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.hashuser'),
            preserve_default=False,
        ),
    ]
