# Generated by Django 5.0.3 on 2024-04-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0002_remove_track_artist_name_remove_track_artist_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(default=-1),
        ),
    ]
