# Generated by Django 5.0.3 on 2024-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0003_track_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_data',
            field=models.CharField(default='', max_length=200),
        ),
    ]
