# Generated by Django 5.0.3 on 2024-04-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0005_rename_release_data_track_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='chill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
