# Generated by Django 5.0.3 on 2024-04-11 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0006_track_chill_track_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
