# Generated by Django 5.0.3 on 2024-04-11 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRSpotify', '0007_track_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
